---
title: "Analysts' Guide"
date: "Last updated: `r Sys.Date()`"
author: "statistics.development@education.gov.uk"
site: "_site.yml"
---

```{r include=FALSE}
library(fontawesome)
library(quarto)

```

---

This website is a guide aimed at anyone working in analysis or statistics in the Department for Education (DfE). It includes tips on best practice and learning resources across a number of areas.

We hope it can prove a useful community driven resource for everyone from the most experienced analyst right through to those just starting out. If you have any feedback, suggested additions, or wish to challenge any of the guidance, feel free to use the GitHub links to suggest changes directly, or contact us at the email you can find at the bottom of the page.

## Test internal videos

### Internal videos from sharepoint

Using a direct link to the mp4 file

{{< video https://educationgovuk.sharepoint.com/:v:/r/sites/lveesfa00074/Data%20Insights%20and%20Statistics%20Division/Learning%20videos/Introduction%20to%20working%20with%20Git.mp4?csf=1&web=1&e=7diTMu >}}

Using an iframe

<iframe src="https://educationgovuk.sharepoint.com/sites/lveesfa00074/_layouts/15/embed.aspx?UniqueId=5f4c1808-530d-4232-8990-7b332ba918cb&embed=%7B%22ust%22%3Atrue%2C%22hv%22%3A%22CopyEmbedCode%22%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen title="Introduction to working with Git.mp4"></iframe>

### Using YouTube to host a publicly available (but not listed) video

direct link to youtube

{{< video https://youtu.be/D60UU5r_TrM?si=ocdhKfT0-UmB_yUJ >}}

iframe

<iframe width="560" height="315" src="https://www.youtube.com/embed/D60UU5r_TrM?si=ocdhKfT0-UmB_yUJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## Learning and development

[Learning support](learning-development/learning-support.html)
- Useful learning resources, and support to get you started

[SQL](learning-development/sql.html)
- Guidance and tips for accessing data via databases with SQL

[R](learning-development/r.html)
- Guidance and tips for using R

[Git](learning-development/git.html)
- Guidance and tips for version control with Git

[Python](learning-development/python.html)
- Guidance and tips for using Python

[Accessibility](learning-development/accessibility.html)
- Tools and resources for digital accessibility

## Statistics production

[Routes for publishing](statistics-production/pub.html)
- Guidance for how to publish different types of statistics

[RAP in statistics](RAP/rap-statistics.html)
- Detailed RAP guidance for statistics publications

[Open data standards](statistics-production/ud.html)
- Guidance on how to structure data files

[Statistics API data standards](statistics-production/api-data-standards.html)
- Guidance on the standards to meet for API data sets

[Explore education statistics (EES)](statistics-production/ees.html)
- Tips on using the explore education statistics service

[Good examples in EES](statistics-production/examples.html)
- Good practice examples in the explore education statistics service

[Embedded visualisations in EES](statistics-production/embedded-charts.html)
- How to embed R Shiny charts in EES publications

[Publication scrums](statistics-production/scrums.html)
- Information on the scrums we run and tips for writing statistical commentary

[User engagement](statistics-production/user-eng.html)
- Guidance on understanding and engaging with the users of published statistics

[EES analytics](statistics-production/user-analytics.html)
- Understanding how users are interacting with your publications

## Writing and visualising

[Public dashboards](writing-visualising/dashboards.html)
- Guidance for publishing public facing statistics dashboards

[Publishing an R Shiny based dashboard](writing-visualising/dashboards_rshiny.html)
- Guidance for publishing public facing statistics dashboards using R Shiny

[Visualising data](writing-visualising/visualising.html)
- Resources and best practice to guide you when visualising data

[Writing about data](writing-visualising/writing.html)
- Resources and best practice for writing about data

## Reproducible Analytical Pipelines (RAP)

[RAP in statistics](RAP/rap-statistics.html)
- Detailed RAP guidance for statistics publications

[RAP expectations](RAP/rap-expectations.html)
- Guidance for all analysts on expectations of RAP

[RAP support](RAP/rap-managers.html)
- Details on support available for RAP in DfE

[RAP FAQs](RAP/rap-faq.html)
- Frequently asked questions about RAP

## Analytical Data Access (ADA) and Databricks

[Analytical Data Access (ADA) and Databricks](ADA/ada.html)
- Guidance for analysts on how to interact with and use data stored in ADA using Databricks

[Databricks Fundamental Concepts](ADA/databricks_fundamentals.qmd)
- Fundamental concepts in DataBricks that will help  you navigate and understand the platform

[Databricks Notebooks](ADA/databricks_notebooks.qmd)
- Guidance on Notebooks in DataBricks

[Databricks Workflows](ADA/databricks_workflows.qmd)
- Guidance on Workflows in DataBricks

[Setup Databricks SQL Warehouse with RStudio](ADA/databricks_rstudio_sql_warehouse.html)
- Guidance for analysts on how to connect to a Databricks SQL Warehouse from RStudio.

[Setup Databricks personal cluster Warehouse with RStudio](ADA/databricks_rstudio_personal_cluster.html)
- Guidance for analysts on how to connect to a Databricks personal cluster from RStudio.


## Contact us

Our mailbox is always monitored and is available for anyone in DfE to ask questions about statistics, whether that is about RAP, building dashboards, coding support, learning and development or statistics publications.

- [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk)
- 9am-5pm, Monday-Friday, aim to reply within 1-2 days