---
  title: "Analytical Data Access (ADA) and databricks"
---
  
  <p class="text-muted">Guidance for analysts on how to interact with and use data stored in ADA using databricks</p>
    
---

# About the ADA project

---

The [Analytical Data Access (ADA) service](https://analytical-data-access.azurewebsites.net/) has been created to support analysts, engineers and policy team members.

It brings together:

*	a searchable data catalogue - the Data Discovery Platform (DDP)
*	a workbench of tools for analysing data - including Databricks
*	a form for requesting access to data
*	a support section - with walkthrough instructions
*	a collection of data reports and dashboards
*	a news and updates area.

As long as you're connected to the network - it's available to anyone who works for the Department of Education.

See these [Databricks support notebooks](https://adb-6882499576863257.17.azuredatabricks.net/browse/folders/3070168888967918?o=6882499576863257#) for more detailed reference guides into how we have setup the service here at DfE, including more information on workspaces, environments, notebooks, clusters, catalogs etc. 


---

# Plans for the future

---

The ambition is to enable access to all datasets across DfE and ESFA and retire the legacy applications. This will create common ways of working.

---

# Useful links

---

## How Databricks works

See the [ADA support page on how Databricks works](https://analytical-data-access.azurewebsites.net/get-support/how-databricks-works).


---

## Walkthrough a simple analysis

See the [ADA support page on using R, python and SQL in Databricks](https://analytical-data-access.azurewebsites.net/get-support/using-r-python-and-sql-in-databricks)


---

## Helpful getting started videos

See the collection of [getting started videos](https://educationgovuk.sharepoint.com/:f:/r/sites/ADA-SuperUserForum/Shared%20Documents/General/Getting%20started%20videos?csf=1&web=1&e=RCFSib) covering the basics of Databricks and using notebooks. 

---

## Databricks code templates

See examples and code snippets in R, SQL and Python in these [Databricks code template notebooks](https://adb-6882499576863257.17.azuredatabricks.net/browse/folders/3070168888967919?o=6882499576863257#)
