---
title: "RAP support"
---

<p class="text-muted">This page outlines the support available for RAP in DfE</p>

---

## Support on offer

Learning resources and materials for [SQL](../learning-development/sql.html), [R](../learning-development/r.html), and [Git](../learning-development/git.html)

---

### Email support

---

 * [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk)  
 * 9-5, aim to reply between 1-2 days.

---

### Technical workshops

---

 *	In person workshops covering specific technical skills in practice
 *	3 hours long, with people working in small groups
 *	We currently offer two workshops: introduction to git and Azure DevOps, and introduction to R and RAP. We can travel to your site to deliver these. 
 * Contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk) to register interest in workshops happening at your site or to request new topics!

We’re also considering a dedicated G6 / G7 programme to build confidence and set expectations. This may include:

 * A 2-hour workshop explaining what teams are expected to do when creating and publishing statistics. Including tools and skills required, RAP, using EES, content design, release clearance, UE + ongoing publishing and where teams can go for help.
 * There will be take away materials that cover lines to take and where to get support.
 * All G6s and G7s are expected to do this, with repeats running to ensure everyone gets a chance to attend.
 
Keep an eye out on Teams for this programme being advertised and contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk) if you'd like to discuss it.

---

## Partnership programme

The Statistics Development Team invites teams to take part in our partnership programme. The programme can help individuals with:

* Using a relevant project to develop new coding skills and improving current confidence
* Streamlining data production processes to free up time for secondary analysis
* Improving the presentation and consistency of statistical products for users

The partnership programme is a great opportunity to work with the Statistics Development Team, using protected time to work on things that are otherwise usually deprioritised. We understand the pressures of BAU work mean that development time is often hard to fit in, but this programme offers designated support and clear project planning from our team so that these improvements can be achieved. Putting in the work at these early stages will save more time and resource in the long run, and we are keen to support as many teams as possible to free up time in the future for even more interesting analysis.

**The Ask**

We ask that you/a designated member of your team are given protected time to work on a specific project, with support from us. Some examples of previous projects we have helped support are:

* The automation of the SEN2 release, creating automated QA reports and all EES outputs at the click of a button.
* The automation of the HoP rolling brief document, removing arduous tasks like copying, pasting, and formatting in Word.

The time commitment of the programme will be dependent on the size of the work and what level of support is required. [Please get in touch with us](mailto:Statistics.DEVELOPMENT@education.gov.uk) if you are interested and would like to discuss further.

---
