---
title: "Accessibility in EES"
---

<p class="text-muted">

Guidance for how to make sure content is accessible in the Explore Education Statistics platform

</p>

---

Explore Education Statistics (EES) is the Department's official statistics dissemination platform, designed to make DfE's published statistics and data easier to find, access, use and understand. We continually work to ensure that the service is as accessible as possible, however some elements of accessibility are directly related to the content produced in the platform, and this is where [better sentence here].

To make suggestions for things to add to this page, or for any advice and support on accessibility in Explore Education Statistics (EES), please contact the [EES support mailbox](mailto:explore.statistics@education.gov.uk).

<div class="alert alert-dismissible alert-danger">
This page is still in development. For the time being refer to the [making your publication exqu-EES-ite: accessibility in releases slides](https://educationgovuk.sharepoint.com/:p:/r/sites/lvewp00086/SSU%20%20open%20sharing/Explore%20Education%20Statistics/Make%20your%20publications%20exqu-EES-ite/Session%202%20-%20accessibility%20in%20content.pptx?d=w0111456d736e4fbaa72f4ce265017b48&csf=1&web=1&e=6bKZ9L){target="_blank" rel="noopener noreferrer"} for guidance</div>

---

# Creating visualisations

---

Some intro text on visualisations, covers tables, charts, and images...

---

## Using charts

General intro to how they work in EES

---

## Choosing a chart

Add in table, with links to guidance.

---

## Line charts

Label lines directly, avoid data point symbols

---

## Colour in charts

A lot to go into here, but basically, do not rely on colour alone.

---

## Alternative text

Definition

---

### Places it is used in EES

---

Good alt text:
* tells people what information the image provides
* describes the content and function of the image
* is specific, meaningful and concise
* uses normal punctuation, like commas and full stops, so the text is easy to read and understand
* is not longer than 2 sentences in most situations

Do not write alt text that:
* includes the name of the photographer or person who created the image
* starts with ‘Image of’, ‘Graphic of’ or common information that would repeat across every image
* repeats information from the page
* includes extra information not in the image

Link to further information on alt text

---

### Handling duplication

---

Comment on general advice. Times when often you'll not have alt text.

EES specific example handling duplication and pointing to text elsewhere.

---

## Images

Where are images used in EES

---

### Format

---

Use SVGs

Examples of exporting as SVG from excel, R etc

---

### Avoid text

---

More on why to avoid text and add example?

---

## Using tables

Where you use them, how they differ from data blocks

---

### Header row

---

All should have one, why it's important, don't just use bold!

How to do it well

---

### Captions

---

All should have one

How to do it well

---

### Copying from word

---

Check caption and headers

---

# Written content

---

How we write is often as important for accessibility as the publishing platform we use. Research shows that [higher literacy people prefer plain English](https://gds.blog.gov.uk/2014/02/17/guest-post-clarity-is-king-the-evidence-that-reveals-the-desperate-need-to-re-think-the-way-we-write/) because it allows them to understand the information as quickly as possible.

We recommend you regularly review the written content you produce, if you'd like help with this, have a look at the publication scrums that we offer. These are a great opportunity

To avoid confusion, technical terms are fine to use, and often are unavoidable, you just need to explain what they mean in plain English when you use them. Treat it as an opportunity to teach your users the terminology.

For more detailed guidance on writing for Explore Education Statistics, have a look at [our writing and visulising guidance](cd.html), and the [GDS content design pages](https://www.gov.uk/guidance/content-design/writing-for-gov-uk){target="_blank" rel="noopener noreferrer"}.

---

## Using headings

How to use them in EES

---

### Structuring headings

---

Cover the ordering and logic

---

### Common pitfalls

---

Don't use bold

Don't have them overly long

Make sure they're understandable out of context

---

## Whitespace

Don't have blank headers for this

Don't have excessive lines

Headers already give you enough space

---

## Footnotes

Just don't do them.

---

# Hyperlinks

---

Link text best practice

---

## Common pitfalls

So many


Give examples of how they could be improved

---
