---
title: "Databricks"
---

<p class="text-muted">A collection of useful learning resources, and information on support and resources to get you started</p>

---


## Databricks resources

There are various learning resources available to help you with upskilling in Databricks.

- [ADA's Analytics Workbench](https://analytical-data-access.azurewebsites.net/workbench): an overview of using Databricks with various analytical tools
- [Databricks Code & Learn GitHub repository](https://github.com/dfe-analytical-services/databricks_code_learn): a repository of training materials and exercises created by Nick Treece (DISD)
- YouTube videos:
    - [What is Databricks SQL?](https://www.youtube.com/watch?v=0XWf1V40SdI&list=PLTPXxbhUt-YXXXlfUPTmlpJ7jvw9KTGAv): a quick intro to using Databricks SQL editor
    - [Genie Code: Your autonomous AI partner](https://www.youtube.com/watch?v=UO0wvGYu5QQ): Using the Genie Code AI assistant within Databricks
    - [Getting Started on Databricks SQL for Users](https://www.youtube.com/watch?v=xOxASzUHg_s&list=PLTPXxbhUt-YXXXlfUPTmlpJ7jvw9KTGAv&index=13): walkthrough of the SQL editor, SQL warehouses, Catalog Explorer, writing SQL queries, creating dashboards and workflows
    - [Learn Databricks in Under 2 Hours](https://www.youtube.com/watch?v=CoqZTt528ew): a longer video showing many different areas of Databricks

---

## Useful links

### ADA support page

---

See the [ADA support page on how Databricks works](https://analytical-data-access.azurewebsites.net/get-support/how-databricks-works).

---

### Databricks jargon buster

The core concepts of Databricks and any related acronyms are explained in the [jargon buster](https://analytical-data-access.education.gov.uk/get-support/jargon)

---

### Walkthrough a simple analysis

---

See the [ADA support page on using R, python and SQL in Databricks](https://analytical-data-access.azurewebsites.net/get-support/using-r-python-and-sql-in-databricks).

---

### Helpful getting started videos

---

See the collection of [getting started videos](https://educationgovuk.sharepoint.com/:f:/r/sites/ADA-SuperUserForum/Shared%20Documents/General/Getting%20started%20videos?csf=1&web=1&e=RCFSib) covering the basics of Databricks and using notebooks. 

---
