---
title: "Learning support"
---

<p class="text-muted">A collection of useful learning resources, and information on support and resources to get you started</p>

---

::: {.callout-tip}
## Git DevOps guidance
You can find helpful guidance on DevOps on [Azure DevOps for Analysis](https://dfe-analytical-services.github.io/azure-devops-for-analysis/index.html). 
:::

---

## Tools and support channels

As analysts and statistics producers, we require a variety of tools to efficiently and reliably work with our data. Below are the recommended tools that give us the most power to do what we need. These have large user communities in DfE, and are already working in our current IT setup.

For best practice when using software and coding in our process, see our [guidance on RAP expectations](../RAP/rap-expectations.html) and the [DfE Good Code Practice guide](https://dfe-analytical-services.github.io/good-code-practice/index.html).

You can also access support on a variety of topics on the [cross-government Digital Slack instance](https://x-govuk.github.io/posts/how-to-use-cross-government-slack/). Some useful channels to join are `#accessibility`, `#ai`, `#data-science` and `#datavis`. 

There is also a [cross-government data science Slack instance](https://govdatascience.slack.com/). Some useful channels to join are `#chat-r`, `#chat-python`, `#info-events` and `#community-rap`.

In DfE, you can also seek advice via Teams. Some useful groups are [Statistics production and publishing](https://teams.microsoft.com/l/team/19%3Ae3c8551e86094e259a60848fcff4dbc1%40thread.skype/conversations?groupId=679b2376-8c8c-4062-a1c9-0744ce5ac88f&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9), [DfE R community](https://teams.microsoft.com/l/team/19%3A311ec2e4d46b4dd38f0d61f05fb93383%40thread.skype/conversations?groupId=b95c605d-8fbc-4e4d-9a76-2f7d1c55e70a&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9), [DfE Python community](https://teams.microsoft.com/l/team/19%3A74b8d5bbf49644f2882fcc4274c03a70%40thread.tacv2/conversations?groupId=1238e58a-44e4-4d0d-bb1f-dcefa3d2e64f&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9) and [DfE Analyst Network](https://teams.microsoft.com/l/team/19%3A50f82a2718184a0e98ba86c3d411a02f%40thread.skype/conversations?groupId=6572094f-43a3-4537-bcf0-fc27dc6557ed&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9).

---

## Email support

For questions about publishing statistics, the statistics Code of Practice or how your statistics publication should be badged, please contact the [HoP Office](mailto:hop.statistics@education.gov.uk).

For support in data harmonisation and data structuring standards, or support with analytical digital services including the explore education statistics service, and deploying and maintaining R Shiny applications contact the [explore education statistics platforms team](mailto:explore.statistics@education.gov.uk).

For any technical questions about R, Git, SQL, RAP or statistics production, contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk)  
 * This mailbox is monitored between 9-5 and we aim to reply within 2 days
 * No question is too small! We are always happy to help
 
 ---

## Technical workshops

We currently offer two in person workshops covering specific technical skills in practice. Each workshop is around 3 hours long, and you will work in small groups. We travel to deliver workshops based on demand, so please get in touch and let us know if you'd like to join the waiting list in your area for one or both of the sessions. 

Our current workshops are:

**Introduction to Git and Azure DevOps**

In this workshop, we cover:

*	What are git, Azure DevOps and GitHub and what are the differences?
*	How can they help your work?
*	How to start working with git and DevOps in the DfE ecosystem
*	Managing projects and tasks with DevOps Boards
*	Basic version control with git – add/stage, commit, push and pull
*	Working with branches
*	Tracking changes and who made them
*	Merging, pull requests and merge conflicts

**Introduction to R and RAP** 

In this workshop, we cover:

* Setting up an R project
* Writing your own functions
* Aggregating & filtering data
* Using if statements
* Joining data
* Using R to run SQL 
* Creating plots (with ggplot2)

Contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk) to register interest in workshops happening at your site or to request new topics!

---

## Partnership programmes

The Statistics Services Unit offers bespoke partnership programmes for analyst teams across the department, designed as dedicated resource to support development work, either building skills or filling resource gaps to allow improvements in analytical or statistical outputs.

Partnerships are designed as short-term projects, agreed in conjunction with the team and their Grade 6. The maximum length for the majority of partnership programmes will be three months, and the project must be clearly defined at the outset.

The aim of partnership programmes is always to upskill the team throughout the project. For this reason, we require any teams taking part to commit time to upskilling during the partnership and being willing to independently continue the work after the partnership is complete, if appropriate. Any agreed projects must be able to be handed back to the team that owns the work, and they must have the skills to maintain it independently by the time the partnership finishes. To enable this, we can offer a variety of support including signposting to resources, recommending relevant L+D, running team workshops and knowledge share sessions, or peer review and pair programming sessions to work side by side to build up skills during the partnership.   

---

### What could a partnership programme involve?

---

- Flexible skilled resource for your team to support with R, Git, SQL or Databricks
- Help with dedicated upskilling of individuals within your team to enable handover of code at the end of the programme
- Knowledge sharing, including support to make decisions on best practice and accessibility, and peer review
- Support with RAP implementation to allow your team to meet the RAP baseline or best practice criteria

For example, this might be:

- Automating processes such as data manipulation or QA
- Creation of or improvements to R Shiny dashboards
- Reviewing existing analytical code
- Support with moving to Azure DevOps or GitHub
- Creation of interactive QA reports

---

###  Partnership programme tiers

---

We have four levels of support available:

- One-off bespoke support via a team meeting or a workshop, or one-off peer review 
- **Tier 1**: occasional check-in meetings to provide best practice guidance 
- **Tier 2**: hands on support for teams with skills or resource gaps 
- **Tier 3**: designated resource working within your team to write code / complete a project for you, designed for complex projects and with the aim of handing the project back to the team at the end of the partnership for continued iteration and maintenance as appropriate

Teams participating in tiers 1-3 will be assigned a named person from the Statistics Services Unit who will support you in completing the project. During the partnership, there will be regular update meetings and progress reports to help keep the work to the agreed timescale. 

---

### How to get started 

---

Once you have a clear, defined piece of work that you think would be appropriate for a partnership programme, contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk). 

You will be sent a form to complete so that you can outline your project and requirements from us. Once we have received your completed form, we'll have an introductory meeting with your team to discuss the project and agree an appropriate tier and timescales. We will then assess your needs, determine who will be best placed to complete the work, and prioritise it according to our existing workload. Your team will be kept updated throughout the process.

::: {.callout-important}
## Tier 3 programmes
Please note: all new tier 3 partnerships will require sign off at Grade 6 level to ensure that time for skills development within your team can be prioritised in parallel with the work, and to ensure a clear handover plan at the end of the project.
:::



If you are interested in a one off / bespoke workshop or team meeting, please contact [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk) and we will work with your team to meet your development needs. 

---

## R, SQL and Git resources

We also have specific learning resources and materials for [SQL](../learning-development/sql.html), [R](../learning-development/r.html), and [Git](../learning-development/git.html)


---

## General resources

**Google and other web-search engines are the single most powerful learning resource out there**, whether it leads you to a Stack Overflow answer to your problem, or to an online training course, it will have your needs covered. We appreciate that it can be daunting and overwhelming at first though, which is why we're pooling together links to particularly relevant resources on this page. Let us know if there's any you'd like to see added!

- [The DfE Analytics Academy online R training course](https://educationgovuk.sharepoint.com/sites/AnalyticsAcademy798){target="_blank" rel="noopener noreferrer"} - walks you through how to get set up with R, as well as setting tasks using DfE data to learn fundamental skills in R.

- [How to QA](https://dfe-analytical-services.github.io/how-to-qa/index.html){target="_blank" rel="noopener noreferrer"} - a general guide to quality assurance best practice in DfE.

- [DfE Data Science resource tool](https://rsconnect/rsc/DS-Resources/){target="_blank" rel="noopener noreferrer"} - a bank of learning materials, from coffee and coding talks to online guidebooks.

- [ESFA guide to using R and Git](https://rsconnect/rsc/esfa-r-training/){target="_blank" rel="noopener noreferrer"} - take you from the beginning, teaches you how to use RStudio and later on even includes some information on Shiny apps and more complex topics. For more information on RShiny apps, join the [R Shiny Developers teams group](https://teams.microsoft.com/l/channel/19%3A311ec2e4d46b4dd38f0d61f05fb93383%40thread.skype/tab%3A%3A1fc89e11-fa70-473d-b993-df467ca0d459?groupId=b95c605d-8fbc-4e4d-9a76-2f7d1c55e70a&tenantId=fad277c9-c60a-4da1-b5f3-b3b8b34a82f9).

- [Connor Quinn's resources for Data Engineering](https://educationgovuk.sharepoint.com/sites/sarpi/g/SitePages/DataEngineeringResources.aspx){target="_blank" rel="noopener noreferrer"} - for more advanced SQL and database resources this is a fantastic place to go.

- [General data science resources](https://github.com/Chris-Engelhardt/data_sci_guide){target="_blank" rel="noopener noreferrer"} - includes plenty of open-source resources for R and SQL, with Python, Git, and shell included in there too.

- [Awesome lists](https://github.com/sindresorhus/awesome){target="_blank" rel="noopener noreferrer"} and [awesome R](https://github.com/qinwf/awesome-R){target="_blank" rel="noopener noreferrer"} - another great bank of learning resources.

- [Data Science week streams](https://web.microsoftstream.com/group/df01862c-7ad4-4f25-b7f2-df7353af52a9){target="_blank" rel="noopener noreferrer"} - a variety of talks across Data Science within the department.

- [DfE Quality Assurance wiki](https://educationgovuk.sharepoint.com/sites/sarpi/g/SitePages/Quality-Assurance.aspx){target="_blank" rel="noopener noreferrer"} -  much of this is aimed at areas that use modelling, plenty of it is applicable to how we QA our data too.

- [David Sands' Boons of R and Git](https://psysandsy.github.io/boons-r-git.html){target="_blank" rel="noopener noreferrer"} - a helpful guide on why R and Git are worth your time.

---

## Further information


For more information on how to use these tools in analysis and statistics publications, please see the [processes and RAP](../RAP/rap-statistics.html){target="_blank" rel="noopener noreferrer"} page.


This is by no means a finite list of resources, we want this to be added to and for it to develop over time - if you have any resources that you think could be added then we'd love to hear from you, so please email us at [statistics.development@education.gov.uk](mailto:statistics.development@education.gov.uk). 


If you are stuck at all, have any questions, want to find a resource, or even just want a second pair of eyes to double check something, contact us using the envelope in the top left corner and we'll be more than happy to help.


---
